<a href="https://colab.research.google.com/github/FennTheFern/PyTorch-specifically/blob/main/pytorch_fundamentals_cont_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


Creating a range of tensors and tensor-likes

In [ ]:
# Use torch.arange NOT torch.range
# the range created will begin on the first number and
# end just before the second number
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# you can use torch.arange to set starts, stops and steps of a range
trying_time = torch.arange(start=0, end=40, step=4)
trying_time

tensor([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36])

In [ ]:
# You can create tensors from the ranges that you create
# one of the ways is to use the function torch.zeros_like which will replace
# all of your numbers in a range with zeros
ten_zeros = torch.zeros_like(input=trying_time)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor datatypes
there are many different tensor datatypes such as floats, integers, or strings.
**Note:** Tensor datatypes is one of the 3 big error causing aspects of PyTorch
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device (cpu)

In [ ]:
# Float 32 tensor is the default for tensors
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # what datatype is the tensor (e.g. float32 or float16)
                               device=None, # what device is your tensor on
                               requires_grad=False) # wether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors (attributes not functions)

1. Tensors not right datatype - to get datatype from tensor use: `tensor.dtype`
2. Tensors not right shape - to get shape from tensor use: `tensor.shape`
3. Tensors not on the right device - to get device from tensor use: `tensor.device`

In [ ]:
# Create a tensor
Harriot = torch.rand(4, 6)
Harriot

tensor([[0.5602, 0.8073, 0.9394, 0.1965, 0.7377, 0.1173],
        [0.8661, 0.4571, 0.6210, 0.7894, 0.0026, 0.6554],
        [0.3489, 0.5861, 0.6606, 0.5907, 0.7045, 0.6761],
        [0.0326, 0.2158, 0.6327, 0.6929, 0.9425, 0.9128]])

In [ ]:
# Find details of the tensor
print(Harriot)
print(f"Datatype of tensor: {Harriot.dtype}")   #.dtype
print(f"Shape of tensor: {Harriot.shape}")      # .shape
print(f"Device tensor is on: {Harriot.device}") #.device


tensor([[0.5602, 0.8073, 0.9394, 0.1965, 0.7377, 0.1173],
        [0.8661, 0.4571, 0.6210, 0.7894, 0.0026, 0.6554],
        [0.3489, 0.5861, 0.6606, 0.5907, 0.7045, 0.6761],
        [0.0326, 0.2158, 0.6327, 0.6929, 0.9425, 0.9128]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([4, 6])
Device tensor is on: cpu


You can change the type of a tensor with the .type() function

In [ ]:
Harriot = Harriot.type(torch.DoubleTensor)
print(f"Datatype of tensor: {Harriot.dtype}")

Datatype of tensor: torch.float64


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [ ]:
# Create a tensor and add ten to it

tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
#Multiply tensor by 10
tensor * 10


tensor([10, 20, 30])

In [ ]:
# because the answers for the multiplication and addition problems were
# not stored, the tensor resets back to the origianl stored value
tensor

tensor([1, 2, 3])

In [ ]:
# PyTorch has in-built functions like torch.mul, which multiplies tensors for you
# But these are not usually used since the normal operators work fine
torch.mul(tensor, 10)

tensor([10, 20, 30])

### Matrix multiplication
Two main ways of performing multiplication in neural networks and deep learning:
  1. Element-wise multiplication
  2.  Matrix multiplication (dot product)

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work
2. The resulting matrix has the shape of the **outer dimensions**:
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`
* `(3, 8) @ (8, 5)` -> `(3, 5)`

In [ ]:
torch.matmul(torch.rand(2, 3), torch.rand(3, 2))

tensor([[0.4723, 0.7153],
        [0.7959, 1.1111]])

In [ ]:
# Element wise multiplication
# This type of multiplication is where the each individual number is multiplied
# By its counterpart in the other tensor. This means the tensors must be the same
# shape and size for the multiplication to work
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


### PyTorch implements matrix multiplication functionality in the torch.matmul() method.

The main two rules for matrix multiplication to remember are:

The inner dimensions must match:

  (3, 2) @ (3, 2) won't work

  (2, 3) @ (3, 2) will work

  (3, 2) @ (2, 3) will work

The resulting matrix has the shape of the outer dimensions:

  (2, 3) @ (3, 2) -> (2, 2)

  (3, 2) @ (2, 3) -> (3, 3)

Note: "@" in Python is the symbol for matrix multiplication.

Resource: You can see all of the rules for matrix multiplication using torch.matmul() in the PyTorch documentation.

In [ ]:
# matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
tensor

tensor([1, 2, 3])

### One of the most common errors in deep learning is shape errors

In [ ]:
#shapes for matrix mulitpication
tensor_A = torch.tensor([[1, 2],
                        [3, 4],
                        [5, 6]])

tensor_B = torch.tensor([[7, 10],
                          [8, 11],
                          [9, 12]])

#torch.mm (tensor_A, tensor_B) #torch.mm is the same as torch.matmul (it's an alias for writing less code)
torch.matmul(tensor_A, tensor_B)

RuntimeError: ignored

In [ ]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

Two fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**.

A **Transpose** switches the axes or dimensions of a given tensor.

In [ ]:
# .T is the transpose
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [ ]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])
